name: Build

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install requirements with PIP
      run: pip install dnslib requests pyinstaller
    - name: Build GoCentral-DNS
      run: pyinstaller --onefile --icon=yarg-3-icon.ico GoCentral-DNS-Server.py
    - name: VirusTotal Scan
      continue-on-error: true
      uses: crazy-max/ghaction-virustotal@v3
      with:
        vt_api_key: ${{ secrets.VT_APIKEY}}
        request_rate: 4
        files: dist/GoCentral-DNS-Server.exe
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: dist/GoCentral-DNS-Server.exe
